class AppConstants {
  static const List<String> genders = ['Male', 'Female', 'Trans'];
  static const List<String> indianStates = [
    // States
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',

    // Union Territories
    'Andaman and Nicobar Islands',
    'Chandigarh',
    'Dadra and Nagar Haveli and Daman and Diu',
    'Delhi',
    'Jammu and Kashmir',
    'Ladakh',
    'Lakshadweep',
    'Puducherry',
  ];
  static const List<String> languages = [
    'Hindi',
    'English',
    'Marathi',
    'Gujarati',
    'Tamil',
    'Telugu',
    'Bengali',
    'Kannada',
    'Malayalam',
    'Punjabi',
    'Urdu',
    'Odia',
    'Assamese',
    'Sindhi',
    'Sanskrit',
  ];
  static const List<String> astrologySkills = [
    'Vedic Astrology',
    'Western Astrology',
    'Natal Chart Reading',
    'Predictive Astrology',
    'Horary Astrology',
    'Electional Astrology',
    'Mundane Astrology',
    'Medical Astrology',
    'Financial Astrology',
    'Relationship Compatibility',
    'Karmic Astrology',
    'Remedial Astrology',
    'Palmistry',
    'Numerology',
    'Tarot Reading',
    'Gemstone Recommendation',
    'Vastu Shastra',
    'Feng Shui',
    'KP Astrology',
    'Nadi Astrology',
    'Prashna Kundali',
    'Muhurta (Electional)',
    'Dasha Prediction',
    'Transit Analysis',
    'Solar Return Analysis',
    'Lunar Return Analysis',
    'Synastry (Relationship)',
    'Composite Charts',
    'Child Astrology',
    'Career Astrology',
    'Spiritual Astrology',
    'Yogas in Astrology',
    'Ashtakavarga',
    'Shadbala',
    'Vimshottari Dasha',
    'Jaimini Astrology',
    'Tajika Astrology',
    'Hora Astrology',
    'Remedies (Mantras, Yantras)',
    'Vedic Rituals Guidance',
    'Psychological Astrology',
    'Evolutionary Astrology',
    'Locational Astrology',
    'Fixed Star Interpretation',
    'Asteroid Interpretation',
    'Vedic Gemology',
    'Panchang Analysis',
    'Birth Time Rectification',
    'Corporate Astrology',
    'Political Astrology'
  ];

  static const List<String> relationshipStatuses = [
    'Single',
    'In a Relationship',
    'Engaged',
    'Married',
    'Divorced',
    'Widowed',
    'Separated',
    'It\'s Complicated',
  ];

  static const String ASTROLOGER = "ASTROLOGER";
  static const String CLIENT = "CLIENT";
  static const String RAZORPAY = "RAZORPAY";
  static const String WALLET = "WALLET";
  static const String CREDIT = "CREDIT";
  static const String DEBIT = "DEBIT";
}